GameSpace: merge build apk workflows into one
Flamingo-OS/packages_apps_GameSpace pull request #5
Opened 2022-06-27 07:59 UTC by JohnsonRan

2022-06-27 08:17 UTC, JohnsonRan commented
If you want to skip build apk, add [skip] tag before commit msg

2022-06-27 16:44 UTC, npv12 requested changes

2022-06-27 16:44 UTC, npv12 commented on .github/workflows/build_apk.yml
> +    if: ${{ !startsWith(github.event.head_commit.message, '[skip]') }}
pretty useless since you can achieve the same using [skip ci] anyway

2022-06-27 16:44 UTC, npv12 commented on .github/workflows/build_apk.yml
> +        if: ${{ !github.event.pull_request }}
it should work only for commit. `${{ github.event.commit }}` if i am correct. It shouldn't be just for not pull request

2022-06-27 16:44 UTC, npv12 commented on .github/workflows/build_apk.yml
> +      - '.**'
since we have all .** do we need to specifically mention .github/** ?

2022-06-28 03:11 UTC, npv12 commented on .github/workflows/build_apk.yml
> +        if: ${{ !github.event.pull_request }}
```suggestion
        if: ${{ github.event.commits[][distinct] }}
```

2022-06-28 03:11 UTC, npv12 commented on .github/workflows/build_apk.yml
> +        if: ${{ !github.event.pull_request }}
```suggestion
        if: ${{ github.event.commits[][distinct] }}
```

2022-06-28 03:11 UTC, npv12 commented on .github/workflows/build_apk.yml
> +        if: ${{ !github.event.pull_request }}
```suggestion
        if: ${{ github.event.commits[][distinct] }}
```

2022-06-28 03:11 UTC, npv12 commented on .github/workflows/build_apk.yml
> +        if: ${{ !github.event.pull_request }}
```suggestion
        if: ${{ github.event.commits[][distinct] }}
```

2022-06-28 06:01 UTC, merged